/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bpsu.g7sts.cait;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.OverlayLayout;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Xthliene
 */
public class CAIT extends javax.swing.JFrame {

    /**
     * Creates new form CAIT
     */
    public CAIT() {
        UIManager.put("TabbedPane.selectedBackground", Color.red);
        initComponents();
        formMain.setVisible(false);
        registerPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formMain = new JPanel();
        jPanel1 = new JPanel();
        jLabel9 = new JLabel();
        jLabel6 = new JLabel();
        jLabel8 = new JLabel();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel2 = new JLabel();
        left_panel = new JPanel();
        jButton2 = new JButton();
        jButton6 = new JButton();
        jButton7 = new JButton();
        jLabel7 = new JLabel();
        jButton10 = new JButton();
        jButton11 = new JButton();
        jLabel5 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jPanel2 = new JPanel();
        jButton1 = new JButton();
        jPanel9 = new JPanel();
        jPanel10 = new JPanel();
        jPanel11 = new JPanel();
        jLabel19 = new JLabel();
        jPanel12 = new JPanel();
        jLabel20 = new JLabel();
        jPanel13 = new JPanel();
        jLabel21 = new JLabel();
        jScrollPane4 = new JScrollPane();
        jTextArea3 = new JTextArea();
        jLabel22 = new JLabel();
        jLabel23 = new JLabel();
        jLabel24 = new JLabel();
        jLabel25 = new JLabel();
        jPanel14 = new JPanel();
        jLabel26 = new JLabel();
        jLabel27 = new JLabel();
        jLabel28 = new JLabel();
        jLabel29 = new JLabel();
        jLabel30 = new JLabel();
        jPanel27 = new JPanel();
        jPanel28 = new JPanel();
        jPanel29 = new JPanel();
        jLabel55 = new JLabel();
        jPanel30 = new JPanel();
        jLabel56 = new JLabel();
        jPanel31 = new JPanel();
        jLabel57 = new JLabel();
        jScrollPane7 = new JScrollPane();
        jTextArea6 = new JTextArea();
        jLabel58 = new JLabel();
        jLabel59 = new JLabel();
        jLabel60 = new JLabel();
        jLabel61 = new JLabel();
        jPanel32 = new JPanel();
        jLabel62 = new JLabel();
        jLabel63 = new JLabel();
        jLabel64 = new JLabel();
        jLabel65 = new JLabel();
        jLabel66 = new JLabel();
        jPanel33 = new JPanel();
        jPanel34 = new JPanel();
        jPanel35 = new JPanel();
        jLabel67 = new JLabel();
        jPanel36 = new JPanel();
        jLabel68 = new JLabel();
        jPanel37 = new JPanel();
        jLabel69 = new JLabel();
        jScrollPane8 = new JScrollPane();
        jTextArea7 = new JTextArea();
        jLabel70 = new JLabel();
        jLabel71 = new JLabel();
        jLabel72 = new JLabel();
        jLabel73 = new JLabel();
        jPanel38 = new JPanel();
        jLabel74 = new JLabel();
        jLabel75 = new JLabel();
        jLabel76 = new JLabel();
        jLabel77 = new JLabel();
        jLabel78 = new JLabel();
        formAuth = new JPanel();
        jPanel3 = new JPanel();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        jLabel15 = new JLabel();
        jPanel5 = new JPanel();
        jLabel11 = new JLabel();
        signinPanel = new JPanel();
        jTextField2 = new JTextField();
        jButton3 = new JButton();
        jLabel10 = new JLabel();
        jPasswordField2 = new JPasswordField();
        registerPanel = new JPanel();
        jTextField3 = new JTextField();
        jButton4 = new JButton();
        jPasswordField1 = new JPasswordField();
        jPasswordField3 = new JPasswordField();
        jPanel6 = new JPanel();
        signin_tab_button = new JButton();
        register_tab_button = new JButton();
        basePlate = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new OverlayLayout(getContentPane()));

        formMain.setLayout(null);

        jPanel1.setBackground(new Color(44, 47, 134));
        jPanel1.setForeground(new Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel9.setBackground(new Color(255, 255, 255));
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 40, 40, 5);

        jLabel6.setBackground(new Color(255, 255, 255));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 30, 40, 5);

        jLabel8.setBackground(new Color(255, 255, 255));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 20, 40, 5);

        jLabel1.setFont(new Font("Product Sans Black", 0, 30)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("corrective action & improvement tracker");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 1000, 37);

        jLabel3.setBackground(new Color(255, 255, 255));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 46, 350, 1);

        jLabel4.setFont(new Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("the quick brown fox jumps over a lazy dog. pack my box with five dozen liquor jugs.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 50, 620, 16);

        formMain.add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 70);

        jLabel2.setBackground(new Color(0, 0, 0));
        jLabel2.setOpaque(true);
        formMain.add(jLabel2);
        jLabel2.setBounds(0, 70, 1000, 2);

        left_panel.setBackground(new Color(204, 204, 204));
        left_panel.setLayout(null);

        jButton2.setBackground(new Color(133, 26, 40));
        jButton2.setFont(new Font("Product Sans Black", 1, 24)); // NOI18N
        jButton2.setForeground(new Color(255, 255, 255));
        jButton2.setIcon(new ImageIcon(getClass().getResource("/logout-icon.png"))); // NOI18N
        jButton2.setText("logout");
        jButton2.setBorder(null);
        jButton2.setHorizontalAlignment(SwingConstants.LEFT);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        left_panel.add(jButton2);
        jButton2.setBounds(0, 630, 240, 40);

        jButton6.setBackground(new Color(62, 80, 156));
        jButton6.setFont(new Font("Product Sans Black", 1, 24)); // NOI18N
        jButton6.setForeground(new Color(255, 255, 255));
        jButton6.setIcon(new ImageIcon(getClass().getResource("/settings-icon.png"))); // NOI18N
        jButton6.setText("settings");
        jButton6.setBorder(null);
        jButton6.setHorizontalAlignment(SwingConstants.LEFT);
        left_panel.add(jButton6);
        jButton6.setBounds(0, 580, 240, 40);

        jButton7.setBackground(new Color(0, 127, 255));
        jButton7.setFont(new Font("Product Sans Black", 1, 24)); // NOI18N
        jButton7.setForeground(new Color(255, 255, 255));
        jButton7.setIcon(new ImageIcon(getClass().getResource("/progress-icon.png"))); // NOI18N
        jButton7.setText("progress");
        jButton7.setBorder(null);
        jButton7.setHorizontalAlignment(SwingConstants.LEFT);
        left_panel.add(jButton7);
        jButton7.setBounds(0, 160, 240, 40);

        jLabel7.setBackground(new Color(44, 47, 134));
        jLabel7.setFont(new Font("Product Sans Black", 0, 26)); // NOI18N
        jLabel7.setForeground(new Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel7.setText("menu");
        left_panel.add(jLabel7);
        jLabel7.setBounds(0, 10, 80, 40);

        jButton10.setBackground(new Color(0, 127, 255));
        jButton10.setFont(new Font("Product Sans Black", 0, 24)); // NOI18N
        jButton10.setForeground(new Color(255, 255, 255));
        jButton10.setIcon(new ImageIcon(getClass().getResource("/feed-icon.png"))); // NOI18N
        jButton10.setText("reports");
        jButton10.setBorder(null);
        jButton10.setHorizontalAlignment(SwingConstants.LEFT);
        left_panel.add(jButton10);
        jButton10.setBounds(0, 60, 240, 40);

        jButton11.setBackground(new Color(0, 127, 255));
        jButton11.setFont(new Font("Product Sans Black", 1, 24)); // NOI18N
        jButton11.setForeground(new Color(255, 255, 255));
        jButton11.setIcon(new ImageIcon(getClass().getResource("/profile-icon.png"))); // NOI18N
        jButton11.setText("profile");
        jButton11.setBorder(null);
        jButton11.setHorizontalAlignment(SwingConstants.LEFT);
        left_panel.add(jButton11);
        jButton11.setBounds(0, 110, 240, 40);

        jLabel5.setBackground(new Color(51, 51, 51));
        jLabel5.setOpaque(true);
        left_panel.add(jLabel5);
        jLabel5.setBounds(0, 50, 240, 1);

        formMain.add(left_panel);
        left_panel.setBounds(0, 72, 250, 678);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setPreferredSize(new Dimension(750, 1000));
        jPanel2.setLayout(null);

        jButton1.setFont(new Font("Product Sans Black", 0, 14)); // NOI18N
        jButton1.setForeground(new Color(255, 255, 255));
        jButton1.setIcon(new ImageIcon(getClass().getResource("/create-post_icon.png"))); // NOI18N
        jButton1.setText("report an issue");
        jButton1.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 20, 680, 50);

        jPanel9.setBackground(new Color(100, 100, 100));
        jPanel9.setLayout(null);

        jPanel10.setBackground(new Color(51, 51, 51));
        jPanel10.setLayout(null);

        jPanel11.setBackground(new Color(51, 51, 51));
        jPanel11.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(255, 255, 255), 2), "Categories", TitledBorder.RIGHT, TitledBorder.BOTTOM, new Font("Segoe UI", 0, 12), new Color(255, 255, 255))); // NOI18N
        jPanel11.setLayout(null);

        jLabel19.setBackground(new Color(255, 153, 102));
        jLabel19.setFont(new Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel19.setText("<html><center>\n<font color=\"#33FF33\">Environment</font>,\n<font color=\"#66CCFF\">Lifting</font>, \n<font color=\"#FF9999\">IDK</font>, \n<font color=\"#FF9966\">Garbage</font>\n\n");
        jPanel11.add(jLabel19);
        jLabel19.setBounds(10, 6, 340, 20);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(320, 210, 360, 40);

        jPanel12.setBackground(new Color(51, 51, 51));
        jPanel12.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(255, 255, 255), 2), "Department", TitledBorder.RIGHT, TitledBorder.BOTTOM, new Font("Segoe UI", 0, 12), new Color(255, 255, 255))); // NOI18N
        jPanel12.setLayout(null);

        jLabel20.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new Color(102, 255, 255));
        jLabel20.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel20.setText("ENSO");
        jPanel12.add(jLabel20);
        jLabel20.setBounds(10, 6, 150, 20);

        jPanel10.add(jPanel12);
        jPanel12.setBounds(140, 210, 170, 40);

        jPanel13.setBackground(new Color(51, 51, 51));
        jPanel13.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(255, 255, 255), 2), "Severity", TitledBorder.RIGHT, TitledBorder.BOTTOM, new Font("Segoe UI", 0, 12), new Color(255, 255, 255))); // NOI18N
        jPanel13.setLayout(null);

        jLabel21.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new Color(255, 51, 51));
        jLabel21.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel21.setText("HIGH");
        jPanel13.add(jLabel21);
        jLabel21.setBounds(10, 6, 100, 20);

        jPanel10.add(jPanel13);
        jPanel13.setBounds(10, 210, 120, 40);

        jScrollPane4.setBorder(null);

        jTextArea3.setBackground(new Color(51, 51, 51));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea3.setForeground(new Color(255, 255, 255));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac ligula nunc. Sed fringilla consequat mollis. Vestibulum lacus libero, pulvinar ut egestas ut, blandit ut est. Phasellus elementum fringilla lobortis. Donec at fermentum dolor. Fusce ullamcorper metus id lacus sodales pellentesque. Donec pretium tempor feugiat. Cras non mi Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac ligula nunc. Sed fringilla consequat mollis. Vestibulum lacus libero, pulvinar ut egestas ut, blandit ut est. Phasellus elementum fringilla lobortis. Donec at fermentum dolor. Fusce ullamcorper metus id lacus sodales pellentesque. Donec pretium tempor feugiat. Cras non mi non nunc efficitur tincidunt sed sed enim. non nunc efficitur tincidunt sed sed enim.");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBorder(null);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel10.add(jScrollPane4);
        jScrollPane4.setBounds(10, 40, 320, 160);

        jLabel22.setIcon(new ImageIcon(getClass().getResource("/feed_image_sample2.jpg"))); // NOI18N
        jLabel22.setOpaque(true);
        jPanel10.add(jLabel22);
        jLabel22.setBounds(340, 110, 180, 90);

        jLabel23.setIcon(new ImageIcon(getClass().getResource("/feed_image_sample3.jpg"))); // NOI18N
        jLabel23.setOpaque(true);
        jPanel10.add(jLabel23);
        jLabel23.setBounds(530, 10, 143, 190);

        jLabel24.setFont(new Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new Color(255, 255, 255));
        jLabel24.setText("Poor Garbage Collection System");
        jPanel10.add(jLabel24);
        jLabel24.setBounds(10, 10, 310, 30);

        jLabel25.setIcon(new ImageIcon(getClass().getResource("/feed_image_sample1.jpg"))); // NOI18N
        jLabel25.setOpaque(true);
        jPanel10.add(jLabel25);
        jLabel25.setBounds(340, 10, 180, 90);

        jPanel9.add(jPanel10);
        jPanel10.setBounds(0, 50, 690, 260);

        jPanel14.setBackground(new Color(51, 51, 51));
        jPanel14.setLayout(null);

        jLabel26.setFont(new Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel26.setForeground(new Color(255, 255, 255));
        jLabel26.setText("Juan Dela Cruz");
        jPanel14.add(jLabel26);
        jLabel26.setBounds(60, 0, 180, 50);

        jLabel27.setIcon(new ImageIcon(getClass().getResource("/testprofile.jpg"))); // NOI18N
        jPanel14.add(jLabel27);
        jLabel27.setBounds(5, 5, 40, 40);

        jPanel9.add(jPanel14);
        jPanel14.setBounds(0, 0, 240, 50);

        jLabel28.setBackground(new Color(102, 0, 0));
        jLabel28.setIcon(new ImageIcon(getClass().getResource("/downvote_icon.png"))); // NOI18N
        jLabel28.setOpaque(true);
        jPanel9.add(jLabel28);
        jLabel28.setBounds(610, 20, 30, 30);

        jLabel29.setBackground(new Color(102, 102, 0));
        jLabel29.setIcon(new ImageIcon(getClass().getResource("/favorite_icon.png"))); // NOI18N
        jLabel29.setOpaque(true);
        jPanel9.add(jLabel29);
        jLabel29.setBounds(650, 20, 30, 30);

        jLabel30.setBackground(new Color(0, 102, 0));
        jLabel30.setIcon(new ImageIcon(getClass().getResource("/upvote_icon.png"))); // NOI18N
        jLabel30.setOpaque(true);
        jPanel9.add(jLabel30);
        jLabel30.setBounds(570, 20, 30, 30);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(40, 800, 690, 310);

        jPanel27.setBackground(new Color(102, 102, 102));
        jPanel27.setLayout(null);

        jPanel28.setBackground(new Color(200, 200, 200));
        jPanel28.setLayout(null);

        jPanel29.setBackground(new Color(200, 200, 200));
        jPanel29.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "categories", TitledBorder.RIGHT, TitledBorder.BOTTOM, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        jPanel29.setLayout(null);

        jLabel55.setBackground(new Color(255, 153, 102));
        jLabel55.setFont(new Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel55.setForeground(new Color(51, 51, 51));
        jLabel55.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel55.setText("<html><center>\n<font color=\"green\">Environment</font>,\n<font color=\"red\">Lifting</font>, \n<font color=\"orange\">IDK</font>, \n<font color=\"blue\">Garbage</font>\n\n");
        jPanel29.add(jLabel55);
        jLabel55.setBounds(10, 6, 340, 20);

        jPanel28.add(jPanel29);
        jPanel29.setBounds(320, 210, 360, 40);

        jPanel30.setBackground(new Color(200, 200, 200));
        jPanel30.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "department", TitledBorder.RIGHT, TitledBorder.BOTTOM, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        jPanel30.setForeground(new Color(0, 0, 0));
        jPanel30.setLayout(null);

        jLabel56.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel56.setForeground(new Color(0, 102, 102));
        jLabel56.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel56.setText("ENSO");
        jPanel30.add(jLabel56);
        jLabel56.setBounds(10, 6, 150, 20);

        jPanel28.add(jPanel30);
        jPanel30.setBounds(140, 210, 170, 40);

        jPanel31.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "severity", TitledBorder.RIGHT, TitledBorder.BOTTOM, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        jPanel31.setOpaque(false);
        jPanel31.setLayout(null);

        jLabel57.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel57.setForeground(new Color(255, 51, 51));
        jLabel57.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel57.setText("HIGH");
        jPanel31.add(jLabel57);
        jLabel57.setBounds(10, 6, 100, 20);

        jPanel28.add(jPanel31);
        jPanel31.setBounds(10, 210, 120, 40);

        jScrollPane7.setBorder(null);

        jTextArea6.setBackground(new Color(200, 200, 200));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new Font("Arial", 0, 16)); // NOI18N
        jTextArea6.setForeground(new Color(51, 51, 51));
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac ligula nunc. Sed fringilla consequat mollis. Vestibulum lacus libero, pulvinar ut egestas ut, blandit ut est. Phasellus elementum fringilla lobortis. Donec at fermentum dolor. Fusce ullamcorper metus id lacus sodales pellentesque. Donec pretium tempor feugiat. Cras non mi Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac ligula nunc. Sed fringilla consequat mollis. Vestibulum lacus libero, pulvinar ut egestas ut, blandit ut est. Phasellus elementum fringilla lobortis. Donec at fermentum dolor. Fusce ullamcorper metus id lacus sodales pellentesque. Donec pretium tempor feugiat. Cras non mi non nunc efficitur tincidunt sed sed enim. non nunc efficitur tincidunt sed sed enim.");
        jTextArea6.setWrapStyleWord(true);
        jTextArea6.setBorder(null);
        jScrollPane7.setViewportView(jTextArea6);

        jPanel28.add(jScrollPane7);
        jScrollPane7.setBounds(10, 40, 320, 160);

        jLabel58.setIcon(new ImageIcon(getClass().getResource("/feed_image_sample2.jpg"))); // NOI18N
        jLabel58.setOpaque(true);
        jPanel28.add(jLabel58);
        jLabel58.setBounds(340, 110, 180, 90);

        jLabel59.setIcon(new ImageIcon(getClass().getResource("/feed_image_sample3.jpg"))); // NOI18N
        jLabel59.setOpaque(true);
        jPanel28.add(jLabel59);
        jLabel59.setBounds(530, 10, 143, 190);

        jLabel60.setFont(new Font("Product Sans Black", 1, 16)); // NOI18N
        jLabel60.setForeground(new Color(0, 0, 0));
        jLabel60.setText("Poor Garbage Collection System");
        jPanel28.add(jLabel60);
        jLabel60.setBounds(10, 10, 310, 30);

        jLabel61.setIcon(new ImageIcon(getClass().getResource("/feed_image_sample1.jpg"))); // NOI18N
        jLabel61.setOpaque(true);
        jPanel28.add(jLabel61);
        jLabel61.setBounds(340, 10, 180, 90);

        jPanel27.add(jPanel28);
        jPanel28.setBounds(0, 50, 690, 260);

        jPanel32.setBackground(new Color(200, 200, 200));
        jPanel32.setLayout(null);

        jLabel62.setFont(new Font("Product Sans Black", 0, 14)); // NOI18N
        jLabel62.setForeground(new Color(57, 45, 172));
        jLabel62.setText("Tanya Degurechaff");
        jPanel32.add(jLabel62);
        jLabel62.setBounds(50, 0, 160, 40);

        jLabel63.setIcon(new ImageIcon(getClass().getResource("/testprofile.jpg"))); // NOI18N
        jPanel32.add(jLabel63);
        jLabel63.setBounds(2, 2, 36, 36);

        jPanel27.add(jPanel32);
        jPanel32.setBounds(0, 10, 300, 40);

        jLabel64.setBackground(new Color(102, 0, 0));
        jLabel64.setIcon(new ImageIcon(getClass().getResource("/downvote_icon.png"))); // NOI18N
        jLabel64.setOpaque(true);
        jPanel27.add(jLabel64);
        jLabel64.setBounds(610, 20, 30, 30);

        jLabel65.setBackground(new Color(102, 102, 0));
        jLabel65.setIcon(new ImageIcon(getClass().getResource("/favorite_icon.png"))); // NOI18N
        jLabel65.setOpaque(true);
        jPanel27.add(jLabel65);
        jLabel65.setBounds(650, 20, 30, 30);

        jLabel66.setBackground(new Color(0, 102, 0));
        jLabel66.setIcon(new ImageIcon(getClass().getResource("/upvote_icon.png"))); // NOI18N
        jLabel66.setOpaque(true);
        jPanel27.add(jLabel66);
        jLabel66.setBounds(570, 20, 30, 30);

        jPanel2.add(jPanel27);
        jPanel27.setBounds(40, 430, 690, 310);

        jPanel33.setBackground(new Color(100, 100, 100));
        jPanel33.setLayout(null);

        jPanel34.setBackground(new Color(200, 200, 200));
        jPanel34.setLayout(null);

        jPanel35.setBackground(new Color(200, 200, 200));
        jPanel35.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "categories", TitledBorder.RIGHT, TitledBorder.BOTTOM, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        jPanel35.setLayout(null);

        jLabel67.setBackground(new Color(255, 153, 102));
        jLabel67.setFont(new Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel67.setForeground(new Color(51, 51, 51));
        jLabel67.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel67.setText("<html><center>\n<font color=\"green\">Environment</font>,\n<font color=\"red\">Lifting</font>, \n<font color=\"orange\">IDK</font>, \n<font color=\"blue\">Garbage</font>\n\n");
        jPanel35.add(jLabel67);
        jLabel67.setBounds(10, 6, 340, 20);

        jPanel34.add(jPanel35);
        jPanel35.setBounds(320, 210, 360, 40);

        jPanel36.setBackground(new Color(200, 200, 200));
        jPanel36.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "department", TitledBorder.RIGHT, TitledBorder.BOTTOM, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        jPanel36.setForeground(new Color(0, 0, 0));
        jPanel36.setLayout(null);

        jLabel68.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel68.setForeground(new Color(0, 102, 102));
        jLabel68.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel68.setText("ENSO");
        jPanel36.add(jLabel68);
        jLabel68.setBounds(10, 6, 150, 20);

        jPanel34.add(jPanel36);
        jPanel36.setBounds(140, 210, 170, 40);

        jPanel37.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "severity", TitledBorder.RIGHT, TitledBorder.BOTTOM, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        jPanel37.setOpaque(false);
        jPanel37.setLayout(null);

        jLabel69.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel69.setForeground(new Color(255, 51, 51));
        jLabel69.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel69.setText("HIGH");
        jPanel37.add(jLabel69);
        jLabel69.setBounds(10, 6, 100, 20);

        jPanel34.add(jPanel37);
        jPanel37.setBounds(10, 210, 120, 40);

        jScrollPane8.setBorder(null);

        jTextArea7.setBackground(new Color(200, 200, 200));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new Font("Arial", 0, 16)); // NOI18N
        jTextArea7.setForeground(new Color(51, 51, 51));
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(5);
        jTextArea7.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac ligula nunc. Sed fringilla consequat mollis. Vestibulum lacus libero, pulvinar ut egestas ut, blandit ut est. Phasellus elementum fringilla lobortis. Donec at fermentum dolor. Fusce ullamcorper metus id lacus sodales pellentesque. Donec pretium tempor feugiat. Cras non mi Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac ligula nunc. Sed fringilla consequat mollis. Vestibulum lacus libero, pulvinar ut egestas ut, blandit ut est. Phasellus elementum fringilla lobortis. Donec at fermentum dolor. Fusce ullamcorper metus id lacus sodales pellentesque. Donec pretium tempor feugiat. Cras non mi non nunc efficitur tincidunt sed sed enim. non nunc efficitur tincidunt sed sed enim.");
        jTextArea7.setWrapStyleWord(true);
        jTextArea7.setBorder(null);
        jScrollPane8.setViewportView(jTextArea7);

        jPanel34.add(jScrollPane8);
        jScrollPane8.setBounds(10, 40, 320, 160);

        jLabel70.setIcon(new ImageIcon(getClass().getResource("/feed_image_sample2.jpg"))); // NOI18N
        jLabel70.setOpaque(true);
        jPanel34.add(jLabel70);
        jLabel70.setBounds(340, 110, 180, 90);

        jLabel71.setIcon(new ImageIcon(getClass().getResource("/feed_image_sample3.jpg"))); // NOI18N
        jLabel71.setOpaque(true);
        jPanel34.add(jLabel71);
        jLabel71.setBounds(530, 10, 143, 190);

        jLabel72.setFont(new Font("Product Sans Black", 1, 16)); // NOI18N
        jLabel72.setForeground(new Color(0, 0, 0));
        jLabel72.setText("Poor Garbage Collection System");
        jPanel34.add(jLabel72);
        jLabel72.setBounds(10, 0, 310, 30);

        jLabel73.setIcon(new ImageIcon(getClass().getResource("/feed_image_sample1.jpg"))); // NOI18N
        jLabel73.setOpaque(true);
        jPanel34.add(jLabel73);
        jLabel73.setBounds(340, 10, 180, 90);

        jPanel33.add(jPanel34);
        jPanel34.setBounds(0, 50, 690, 260);

        jPanel38.setBackground(new Color(200, 200, 200));
        jPanel38.setLayout(null);

        jLabel74.setFont(new Font("Product Sans Black", 0, 14)); // NOI18N
        jLabel74.setForeground(new Color(57, 45, 172));
        jLabel74.setText("Tanya Degurechaff");
        jPanel38.add(jLabel74);
        jLabel74.setBounds(50, 0, 160, 40);

        jLabel75.setIcon(new ImageIcon(getClass().getResource("/testprofile.jpg"))); // NOI18N
        jPanel38.add(jLabel75);
        jLabel75.setBounds(2, 2, 36, 36);

        jPanel33.add(jPanel38);
        jPanel38.setBounds(0, 10, 300, 40);

        jLabel76.setBackground(new Color(102, 0, 0));
        jLabel76.setIcon(new ImageIcon(getClass().getResource("/downvote_icon.png"))); // NOI18N
        jLabel76.setOpaque(true);
        jPanel33.add(jLabel76);
        jLabel76.setBounds(610, 20, 30, 30);

        jLabel77.setBackground(new Color(102, 102, 0));
        jLabel77.setIcon(new ImageIcon(getClass().getResource("/favorite_icon.png"))); // NOI18N
        jLabel77.setOpaque(true);
        jPanel33.add(jLabel77);
        jLabel77.setBounds(650, 20, 30, 30);

        jLabel78.setBackground(new Color(0, 102, 0));
        jLabel78.setIcon(new ImageIcon(getClass().getResource("/upvote_icon.png"))); // NOI18N
        jLabel78.setOpaque(true);
        jPanel33.add(jLabel78);
        jLabel78.setBounds(570, 20, 30, 30);

        jPanel2.add(jPanel33);
        jPanel33.setBounds(40, 100, 690, 310);

        jScrollPane1.setViewportView(jPanel2);

        formMain.add(jScrollPane1);
        jScrollPane1.setBounds(250, 72, 750, 678);

        getContentPane().add(formMain);

        formAuth.setBackground(new Color(255, 255, 255));
        formAuth.setLayout(null);

        jPanel3.setBackground(new Color(44, 47, 134));
        jPanel3.setForeground(new Color(153, 153, 153));
        jPanel3.setLayout(null);

        jLabel13.setFont(new Font("Product Sans Black", 0, 30)); // NOI18N
        jLabel13.setForeground(new Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel13.setText("corrective action & improvement tracker");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 10, 1000, 37);

        jLabel14.setBackground(new Color(255, 255, 255));
        jLabel14.setOpaque(true);
        jPanel3.add(jLabel14);
        jLabel14.setBounds(350, 46, 350, 1);

        jLabel15.setFont(new Font("Segoe UI", 2, 12)); // NOI18N
        jLabel15.setForeground(new Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel15.setText("the quick brown fox jumps over a lazy dog. pack my box with five dozen liquor jugs.");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(210, 50, 620, 16);

        formAuth.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 70);

        jPanel5.setBackground(new Color(100, 100, 100));
        jPanel5.setLayout(null);

        jLabel11.setForeground(new Color(200, 200, 200));
        jLabel11.setText("<html><p><b>Disclaimer:</b> This version of the software is submitted to <b>Mr. Gabriel Angelo L. Rubia, CSPE, M.Sc. (cand.)</b> at the <b>Bataan Peninsula University</b> as part of the course <b>NGEC0803: Science, Technology, and Society</b>.The authors, the recipient (Mr. Rubia), or the university are not responsible for any use outside its intended purposes.</p>\n");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 0, 990, 40);

        formAuth.add(jPanel5);
        jPanel5.setBounds(0, 710, 1000, 40);

        signinPanel.setBackground(new Color(200, 200, 200));
        signinPanel.setLayout(null);

        jTextField2.setBackground(new Color(200, 200, 200));
        jTextField2.setForeground(new Color(0, 0, 0));
        jTextField2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "email", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        jTextField2.setCaretColor(new Color(0, 0, 0));
        signinPanel.add(jTextField2);
        jTextField2.setBounds(30, 30, 280, 50);

        jButton3.setBackground(new Color(51, 153, 255));
        jButton3.setFont(new Font("Product Sans Black", 1, 12)); // NOI18N
        jButton3.setForeground(new Color(255, 255, 255));
        jButton3.setText("Sign-in");
        jButton3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        signinPanel.add(jButton3);
        jButton3.setBounds(30, 190, 280, 40);

        jLabel10.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new Color(0, 51, 255));
        jLabel10.setText("Forgot Password?");
        signinPanel.add(jLabel10);
        jLabel10.setBounds(120, 160, 100, 16);

        jPasswordField2.setBackground(new Color(200, 200, 200));
        jPasswordField2.setForeground(new Color(0, 0, 0));
        jPasswordField2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "password", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        signinPanel.add(jPasswordField2);
        jPasswordField2.setBounds(30, 100, 280, 50);

        formAuth.add(signinPanel);
        signinPanel.setBounds(330, 250, 350, 260);

        registerPanel.setBackground(new Color(200, 200, 200));
        registerPanel.setLayout(null);

        jTextField3.setBackground(new Color(200, 200, 200));
        jTextField3.setForeground(new Color(0, 0, 0));
        jTextField3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "email", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        jTextField3.setCaretColor(new Color(0, 0, 0));
        registerPanel.add(jTextField3);
        jTextField3.setBounds(30, 30, 280, 50);

        jButton4.setBackground(new Color(51, 153, 255));
        jButton4.setFont(new Font("Product Sans Black", 1, 12)); // NOI18N
        jButton4.setForeground(new Color(255, 255, 255));
        jButton4.setText("Sign-in");
        jButton4.setCursor(new Cursor(Cursor.HAND_CURSOR));
        registerPanel.add(jButton4);
        jButton4.setBounds(30, 240, 280, 40);

        jPasswordField1.setBackground(new Color(200, 200, 200));
        jPasswordField1.setForeground(new Color(0, 0, 0));
        jPasswordField1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "confirm password", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        registerPanel.add(jPasswordField1);
        jPasswordField1.setBounds(30, 170, 280, 50);

        jPasswordField3.setBackground(new Color(200, 200, 200));
        jPasswordField3.setForeground(new Color(0, 0, 0));
        jPasswordField3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(51, 51, 51), 2), "password", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Segoe UI", 1, 12), new Color(51, 51, 51))); // NOI18N
        registerPanel.add(jPasswordField3);
        jPasswordField3.setBounds(30, 100, 280, 50);

        formAuth.add(registerPanel);
        registerPanel.setBounds(330, 250, 350, 310);

        jPanel6.setBackground(new Color(100, 100, 100));
        jPanel6.setLayout(null);

        signin_tab_button.setBackground(new Color(200, 200, 200));
        signin_tab_button.setFont(new Font("Product Sans Black", 1, 14)); // NOI18N
        signin_tab_button.setForeground(new Color(0, 102, 255));
        signin_tab_button.setText("sign-in");
        signin_tab_button.setBorder(null);
        signin_tab_button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        signin_tab_button.addActionListener(this::signin_tab_buttonActionPerformed);
        jPanel6.add(signin_tab_button);
        signin_tab_button.setBounds(10, 10, 80, 40);

        register_tab_button.setBackground(new Color(100, 100, 100));
        register_tab_button.setFont(new Font("Product Sans Black", 1, 14)); // NOI18N
        register_tab_button.setForeground(new Color(200, 200, 200));
        register_tab_button.setText("register");
        register_tab_button.setBorder(null);
        register_tab_button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        register_tab_button.addActionListener(this::register_tab_buttonActionPerformed);
        jPanel6.add(register_tab_button);
        register_tab_button.setBounds(90, 10, 80, 40);

        formAuth.add(jPanel6);
        jPanel6.setBounds(330, 200, 350, 50);

        getContentPane().add(formAuth);

        GroupLayout basePlateLayout = new GroupLayout(basePlate);
        basePlate.setLayout(basePlateLayout);
        basePlateLayout.setHorizontalGroup(basePlateLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        basePlateLayout.setVerticalGroup(basePlateLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        getContentPane().add(basePlate);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabButtonsHovered(ActionEvent evt) {
        
    }
    
    
    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void signin_tab_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_signin_tab_buttonActionPerformed
        registerPanel.setVisible(false);
        signinPanel.setVisible(true);
        register_tab_button.setBackground(new Color(100, 100, 100));
        register_tab_button.setForeground(new Color(200, 200, 200));
        signin_tab_button.setBackground(new Color(200, 200, 200));
        signin_tab_button.setForeground(new Color(0, 100, 255));
    }//GEN-LAST:event_signin_tab_buttonActionPerformed

    private void register_tab_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_register_tab_buttonActionPerformed
        registerPanel.setVisible(true);
        signinPanel.setVisible(false);
        signin_tab_button.setBackground(new Color(100, 100, 100));
        signin_tab_button.setForeground(new Color(200, 200, 200));
        register_tab_button.setBackground(new Color(200, 200, 200));
        register_tab_button.setForeground(new Color(0, 100, 255));
    }//GEN-LAST:event_register_tab_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
             
             
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(CAIT.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel basePlate;
    private JPanel formAuth;
    private JPanel formMain;
    private JButton jButton1;
    private JButton jButton10;
    private JButton jButton11;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton6;
    private JButton jButton7;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel24;
    private JLabel jLabel25;
    private JLabel jLabel26;
    private JLabel jLabel27;
    private JLabel jLabel28;
    private JLabel jLabel29;
    private JLabel jLabel3;
    private JLabel jLabel30;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel55;
    private JLabel jLabel56;
    private JLabel jLabel57;
    private JLabel jLabel58;
    private JLabel jLabel59;
    private JLabel jLabel6;
    private JLabel jLabel60;
    private JLabel jLabel61;
    private JLabel jLabel62;
    private JLabel jLabel63;
    private JLabel jLabel64;
    private JLabel jLabel65;
    private JLabel jLabel66;
    private JLabel jLabel67;
    private JLabel jLabel68;
    private JLabel jLabel69;
    private JLabel jLabel7;
    private JLabel jLabel70;
    private JLabel jLabel71;
    private JLabel jLabel72;
    private JLabel jLabel73;
    private JLabel jLabel74;
    private JLabel jLabel75;
    private JLabel jLabel76;
    private JLabel jLabel77;
    private JLabel jLabel78;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel11;
    private JPanel jPanel12;
    private JPanel jPanel13;
    private JPanel jPanel14;
    private JPanel jPanel2;
    private JPanel jPanel27;
    private JPanel jPanel28;
    private JPanel jPanel29;
    private JPanel jPanel3;
    private JPanel jPanel30;
    private JPanel jPanel31;
    private JPanel jPanel32;
    private JPanel jPanel33;
    private JPanel jPanel34;
    private JPanel jPanel35;
    private JPanel jPanel36;
    private JPanel jPanel37;
    private JPanel jPanel38;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel9;
    private JPasswordField jPasswordField1;
    private JPasswordField jPasswordField2;
    private JPasswordField jPasswordField3;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane7;
    private JScrollPane jScrollPane8;
    private JTextArea jTextArea3;
    private JTextArea jTextArea6;
    private JTextArea jTextArea7;
    private JTextField jTextField2;
    private JTextField jTextField3;
    private JPanel left_panel;
    private JPanel registerPanel;
    private JButton register_tab_button;
    private JPanel signinPanel;
    private JButton signin_tab_button;
    // End of variables declaration//GEN-END:variables
}
