/*
 * Copyright (C) 2025 Xthliene
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package bpsu.g7sts.cait;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.OverlayLayout;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bson.types.ObjectId;

/**
 *
 * @author Xthliene
 */
public class CreatePost extends JDialog {

    /**
     * Creates new form ReportPost
     */
    private Issue postResult = null;
    private CAIT parent;

    public CreatePost(CAIT parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Issue showDialog() {
        parent = (CAIT) this.getOwner();
        setVisible(true);
        return postResult;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPlate = new JPanel();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        txt_Description = new JTextArea();
        txt_Title = new JTextField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jScrollPane2 = new JScrollPane();
        jPanel2 = new JPanel();
        jButton2 = new JButton();
        jcb_Tags = new JComboBox<>();
        jComboBox2 = new JComboBox<>();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jComboBox3 = new JComboBox<>();
        jScrollPane3 = new JScrollPane();
        pane_tagLister = new JPanel();
        jButton6 = new JButton();
        jLabel9 = new JLabel();
        lbl_errorMsg = new JLabel();
        basePlate = new JPanel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new OverlayLayout(getContentPane()));

        mainPlate.setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Description");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 110, 170, 16);

        txt_Description.setColumns(15);
        txt_Description.setLineWrap(true);
        txt_Description.setRows(5);
        txt_Description.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txt_Description);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 560, 80);
        jPanel1.add(txt_Title);
        txt_Title.setBounds(20, 70, 560, 30);

        jLabel2.setText("Title");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 50, 23, 16);

        jLabel3.setText("Tags:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 220, 80, 20);

        jScrollPane2.setBorder(null);
        jScrollPane2.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel2.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 0));
        jScrollPane2.setViewportView(jPanel2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 330, 560, 210);

        jButton2.setText("Submit");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 570, 560, 40);

        jcb_Tags.setModel(new DefaultComboBoxModel<>(new String[] { "Lifting", "Environmental", "Etc", "Other" }));
        jcb_Tags.addActionListener(this::jcb_TagsActionPerformed);
        jPanel1.add(jcb_Tags);
        jcb_Tags.setBounds(20, 240, 120, 20);

        jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] { "LOW", "MEDIUM", "HIGH", "SEVERE" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(430, 270, 150, 20);

        jLabel5.setText("Urgency:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 270, 60, 20);

        jLabel6.setText("Department:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 270, 80, 20);

        jComboBox3.setModel(new DefaultComboBoxModel<>(new String[] { "ENSO", "GSU", "Other" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(100, 270, 130, 20);

        jScrollPane3.setBorder(null);
        jScrollPane3.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pane_tagLister.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 0));
        jScrollPane3.setViewportView(pane_tagLister);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(150, 220, 430, 40);

        jButton6.setText("Attach Image");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel1.add(jButton6);
        jButton6.setBounds(20, 300, 120, 20);

        jLabel9.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel9.setText("CREATE AN ISSUE/NON-COMFORMITY REPORT");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 10, 600, 40);

        lbl_errorMsg.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        lbl_errorMsg.setForeground(new Color(204, 0, 0));
        lbl_errorMsg.setHorizontalAlignment(SwingConstants.CENTER);
        lbl_errorMsg.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt) {
                lbl_errorMsgFocusLost(evt);
            }
        });
        jPanel1.add(lbl_errorMsg);
        lbl_errorMsg.setBounds(30, 540, 550, 20);

        mainPlate.add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 620);

        getContentPane().add(mainPlate);

        GroupLayout basePlateLayout = new GroupLayout(basePlate);
        basePlate.setLayout(basePlateLayout);
        basePlateLayout.setHorizontalGroup(basePlateLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        basePlateLayout.setVerticalGroup(basePlateLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(basePlate);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    ArrayList<PostImage> tmpImages = new ArrayList<>();
    
    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Issue result = new Issue(parent.db);
        String title = txt_Title.getText();
        String description = txt_Description.getText();
        String errorMsg = null;
        if (title.isBlank()) {
            errorMsg = "Title cannot be empty.";
        } else if (description.isBlank()) {
            errorMsg = "Description cannot be empty.";
        } else if (tags.isEmpty()) {
            errorMsg = "You must have at least one tag.";
        }

        if (errorMsg != null) {
            lbl_errorMsg.setText(errorMsg);
            lbl_errorMsg.requestFocus();
            return;
        }
        result.user = parent.user;
        result.title = title;
        result.description = description;
        result.severity = Severity.valueOf(jComboBox2.getSelectedItem().toString());
        result.department = jComboBox3.getSelectedItem().toString();
        result.tags = tags.stream()
            .map(Tags::getText)
                .toList();
        
        if (!tmpImages.isEmpty()) {
            List<ObjectId> imgIds = new ArrayList<>();
            for (PostImage image : tmpImages) {
                imgIds.add(parent.db.uploadImage(image.file));
            }
            result.images = imgIds;
        }
        postResult = result;
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    private final ArrayList<Tags> tags = new ArrayList<>();
    private void jcb_TagsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jcb_TagsActionPerformed
        Object item = jcb_Tags.getSelectedItem();
        tags.add(new Tags(
                item.toString(),
                tags,
                jcb_Tags,
                pane_tagLister
        ));
        jcb_Tags.removeItem(item);     
    }//GEN-LAST:event_jcb_TagsActionPerformed

    private void lbl_errorMsgFocusLost(FocusEvent evt) {//GEN-FIRST:event_lbl_errorMsgFocusLost
        lbl_errorMsg.setText("");
    }//GEN-LAST:event_lbl_errorMsgFocusLost
    
    private void jButton6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Image files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);
        int result = fileChooser.showOpenDialog(this);
        File selectedFile = fileChooser.getSelectedFile();

        while (true) {
            if (result == JFileChooser.APPROVE_OPTION) {
                try {
                    String mimeType = Files.probeContentType(selectedFile.toPath());
                    if (mimeType == null || !mimeType.startsWith("image/")) {
                        JOptionPane.showMessageDialog(this,
                                "Invalid file type! Please select an image.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        result = fileChooser.showOpenDialog(this);
                        selectedFile = fileChooser.getSelectedFile();
                    } else if ((selectedFile.length() / 1024.0 / 1024.0 > 5)) {
                        JOptionPane.showMessageDialog(this,
                                "Image must be less than 5MB.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        result = fileChooser.showOpenDialog(this);
                        selectedFile = fileChooser.getSelectedFile();
                    } else {
                        System.out.println(jPanel2.getComponentCount());
                        tmpImages.add(new PostImage(selectedFile, jPanel2, tmpImages));
                        System.out.println(tmpImages.getLast().file);
                        jPanel2.add(tmpImages.getLast().panel);
                        System.out.println(jPanel2.getComponentCount());
                        jPanel2.revalidate();
                        jPanel2.repaint();
                        break;
                    }
                } catch (HeadlessException | IOException e) {
                    e.printStackTrace();
                }
            } else {
                break;
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel basePlate;
    private JButton jButton2;
    private JButton jButton6;
    private JComboBox<String> jComboBox2;
    private JComboBox<String> jComboBox3;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JComboBox<String> jcb_Tags;
    private JLabel lbl_errorMsg;
    private JPanel mainPlate;
    JPanel pane_tagLister;
    private JTextArea txt_Description;
    private JTextField txt_Title;
    // End of variables declaration//GEN-END:variables
}

class Tags {
    final JPanel panel;
    final JLabel tagText;
    final JButton closeButton;
    public Tags(String tagName, ArrayList list, JComboBox combo, JPanel container) {
        panel = new JPanel();
        tagText = new JLabel(tagName);
        closeButton = new JButton("X");
        
        panel.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        panel.setPreferredSize(new Dimension(120, 20));
        panel.setLayout(null);
        closeButton.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        closeButton.addActionListener((evt) -> {
            combo.addItem(tagName);
            list.remove(this);
            container.remove(panel);
            container.revalidate();           
            container.repaint();
        });
        
        panel.add(closeButton);
        panel.add(tagText);
        
        closeButton.setBounds(100, 0, 20, 20);
        tagText.setBounds(10, 0, 90, 20);
        container.add(panel);
    }
    public String getText() {
        return tagText.getText();
    }
} 

class PostImage {
    final JPanel panel; 
    final JButton button;
    final File file;
    public PostImage(File f, JPanel parent, ArrayList list) {
        file = f;
        panel = new JPanel();
        button = new JButton("X");
        JLabel label = new JLabel();
        panel.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        panel.setPreferredSize(new Dimension(200, 200));
        panel.setLayout(null);
        panel.setBackground(Color.WHITE);
        button.setFont(new Font("Segoe UI", 1, 8));
        button.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        panel.add(button);
        button.setBounds(180, 0, 20, 20);
        label.setHorizontalAlignment(SwingConstants.CENTER);
        label.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
        ImageIcon icon = new ImageIcon(file.getAbsolutePath());
        Image img = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));
        panel.add(label);
        System.out.println(button.getText());
        label.setBounds(0, 0, 200, 200);
        parent.add(panel);
        parent.revalidate();
        parent.repaint();
        button.addActionListener(evt -> {
            parent.remove(panel);
            parent.revalidate();
            parent.repaint();
            list.remove(this);
        });
    }
}